language: node_js

node_js:
  - 4
  - 5
  - 6
  - 7
  - 8

notifications:
  slack:
    rooms:
      - secure: "aQJ9JcOHsTNMl9dB6ET9OM5B4l/EfW+K65FOTcNsGsq12t0iJalDvoBhSCLZXvo1Jf1bX6WFYelXtTrlVPT5T12/6NjCrHC6XARqWYhoRVzsUeRUKYEDPweOvdaJL4cC5Qe0xIrZsKejGzRsYXl/wFN8LjkoiWWPDAQUQ061Y0D3CejY2pyvcOE3GwWe7ezUnwKJTr588FFyYDc0Q5FIcduxmEeqh99h/Xg9VsTSP/CKxyI9YKmR+cwvHP6gch6h2f6UPDnnWBmvM3Qiahi4ZrpE3mXOfatp08AuhcicMEsMXhYgkn55E3w03jLRVF11Gy6FvOdQBoaP3rmkXzwgwiZztSpmxXtrub3zLJxhG0fzzA/IitcQtu7uXFF9TvDnekJYl8hu/3w4zuuqk5V/LuEYFRgOcsF5484TZh3fPX6O5oCLFeYSViC2aK2azvi+smOJiFpcaQ9K3YPqbpXW6GQWJue9OIrmZasSwqmyXCD0q5KPHB7GNw90wbpKh5OEA0W/nupqvlvaXLUkRjEbX01KisynRIPHXn8hznc8pjQm7a/HkKA2zZaHYztofRPWcWdN0xIzJewyHF3hpr5eTHHgZoV6jsRjZ5Itd4EjaZFj2C3V9Qz4g1JVDX6klxa1hiff5m3fx8c2kWZbjsk2tggWZdFj91EUu3TJGBwEWME="
    on_success: always
